name: Generate sitemap

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://dnyaneshwarware.github.io
        include-pdf: true # Since you're a PDF metadata expert!

    - name: Commit and push the sitemap
      run: |
        if [[ `git status --porcelain sitemap.xml` ]]; then
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add sitemap.xml
          git commit -m "Automated sitemap update"
          git push
        fi
        
